stages:
  # Development stages
  - deploy_dev_db
  - deploy_dev_flask
  - deploy_dev_mss

  # Preview stages
  - deploy_prev_db
  - deploy_prev_flask
  - deploy_prev_mss

  # Production stages
  - deploy_main_db
  - deploy_main_flask
  - deploy_main_mss

variables:
  # .env.local
  MSS_SLACK_VERIFICATION_TOKEN: $MSS_SLACK_VERIFICATION_TOKEN
  MSS_SLACK_SIGNING_SECRET: $MSS_SLACK_SIGNING_SECRET
  MSS_SLACK_WEBHOOK_URL: $MSS_SLACK_WEBHOOK_URL
  MSS_SLACK_CHANNEL: $MSS_SLACK_CHANNEL

  # Disable Logic
  PG_DB_DISABLE_DEPLOY: $PG_DB_DISABLE_DEPLOY

  # Container Name Elements
  NAME_PREFIX: ${CI_COMMIT_BRANCH}-
  NAME_SUFFIX_DB: pg
  NAME_SUFFIX_FLASK: flask
  NAME_SUFFIX_MSS: mss

  # Project Name
  PROJECT_NAME: ${CI_COMMIT_BRANCH}-${CI_PROJECT_NAME}

  # Environment Names
  ENVIRONMENT_NAME_DB: ${CI_COMMIT_BRANCH}-${CI_PROJECT_NAME}-${NAME_SUFFIX_DB}
  ENVIRONMENT_NAME_FLASK: ${CI_COMMIT_BRANCH}-${CI_PROJECT_NAME}-${NAME_SUFFIX_FLASK}
  ENVIRONMENT_NAME_MSS: ${CI_COMMIT_BRANCH}-${CI_PROJECT_NAME}-${NAME_SUFFIX_MSS}

  # Environment URLs
  ENVIRONMENT_URL_DB: https://${CI_COMMIT_BRANCH}-${CI_PROJECT_NAME}-${NAME_SUFFIX_DB}.${DOMAIN_NAME}:${BALANCER_PORT}
  ENVIRONMENT_URL_FLASK: https://${CI_COMMIT_BRANCH}-${CI_PROJECT_NAME}-${NAME_SUFFIX_FLASK}.${DOMAIN_NAME}:${BALANCER_PORT}
  ENVIRONMENT_URL_MSS: https://${CI_COMMIT_BRANCH}-${CI_PROJECT_NAME}-${NAME_SUFFIX_MSS}.${DOMAIN_NAME}:${BALANCER_PORT}

  # Local FLASK base URL
  MSS_FLASK_BASE_URL: http://$ENVIRONMENT_URL_FLASK

.deploy_db_template: &deploy_db_template
  script:
    - docker-compose -p $PROJECT_NAME -f docker-compose-prod.yml down --volumes --remove-orphans powertwin-solver-pg
    - echo "Building Docker image for DB in $CI_COMMIT_BRANCH environment..."
    - docker-compose -p $PROJECT_NAME -f docker-compose-prod.yml build --force-rm --no-cache powertwin-solver-pg
    - echo "Deploying DB Docker container to $CI_COMMIT_BRANCH environment..."
    - docker-compose -p $PROJECT_NAME -f docker-compose-prod.yml up -d powertwin-solver-pg
    - echo "DB Deployed @ ${ENVIRONMENT_URL_DB}"
  after_script:
    - echo "DB deployment to $CI_COMMIT_BRANCH complete"
  when: on_success

.deploy_flask_template: &deploy_flask_template
  script:
    - docker-compose -p $PROJECT_NAME -f docker-compose-prod.yml down --volumes --remove-orphans powertwin-solver-flask
    - echo "Building Docker image for FLASK in $CI_COMMIT_BRANCH environment..."
    - docker-compose -p $PROJECT_NAME -f docker-compose-prod.yml build --force-rm --no-cache powertwin-solver-flask
    - echo "Deploying FLASK Docker container to $CI_COMMIT_BRANCH environment..."
    - docker-compose -p $PROJECT_NAME -f docker-compose-prod.yml up -d powertwin-solver-flask
    - echo "FLASK Deployed @ ${ENVIRONMENT_URL_FLASK}"
  after_script:
    - echo "FLASK deployment to $CI_COMMIT_BRANCH complete"
  when: on_success

.deploy_mss_template: &deploy_mss_template
  script:
    - docker-compose -p $PROJECT_NAME -f docker-compose-prod.yml down --volumes --remove-orphans powertwin-db-mss
    - echo "Building Docker images for Microservices in $CI_COMMIT_BRANCH environment..."
    - docker-compose -p $PROJECT_NAME -f docker-compose-prod.yml build --force-rm --no-cache powertwin-db-mss
    - echo "Deploying Microservices Docker container to $CI_COMMIT_BRANCH environment..."
    - docker-compose -p $PROJECT_NAME -f docker-compose-prod.yml up -d --no-deps powertwin-db-mss
    - echo "Microservices Deployed @ ${ENVIRONMENT_URL_MSS}"
  after_script:
    - echo "Microservices deployment to $CI_COMMIT_BRANCH complete"
  when: on_success

# Development Environment
deploy_dev_db:
  stage: deploy_dev_db
  tags:
    - tank
  variables:
    FLASK_PORT: 5443
    PG_DB_PORT: 5333
    MSS_PORT: 5113
    PG_DB_COLLECTION_ID: 1
  <<: *deploy_db_template
  environment:
    name: $ENVIRONMENT_NAME_DB
    url: $ENVIRONMENT_URL_DB
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" && $PG_DB_DISABLE_DEPLOY != "true"'

deploy_dev_flask:
  stage: deploy_dev_flask
  tags:
    - tank
  variables:
    FLASK_PORT: 5443
    PG_DB_PORT: 5333
    MSS_PORT: 5113
    PG_DB_COLLECTION_ID: 1
  <<: *deploy_flask_template
  environment:
    name: $ENVIRONMENT_NAME_FLASK
    url: $ENVIRONMENT_URL_FLASK
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'

deploy_dev_mss:
  stage: deploy_dev_mss
  tags:
    - tank
  variables:
    FLASK_PORT: 5443
    PG_DB_PORT: 5333
    MSS_PORT: 5113
    PG_DB_COLLECTION_ID: 1
  <<: *deploy_mss_template
  environment:
    name: $ENVIRONMENT_NAME_MSS
    url: $ENVIRONMENT_URL_MSS
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" && $MSS_DISABLE_DEPLOY != "true"'

# Preview Environment
deploy_prev_db:
  stage: deploy_prev_db
  tags:
    - tank
  variables:
    FLASK_PORT: 5444
    PG_DB_PORT: 5334
    MSS_PORT: 5114
    PG_DB_COLLECTION_ID: 1
  <<: *deploy_db_template
  environment:
    name: $ENVIRONMENT_NAME_DB
    url: $ENVIRONMENT_URL_DB
  rules:
    - if: '$CI_COMMIT_BRANCH == "prev" && $PG_DB_DISABLE_DEPLOY != "true"'

deploy_prev_flask:
  stage: deploy_prev_flask
  tags:
    - tank
  variables:
    FLASK_PORT: 5444
    PG_DB_PORT: 5334
    MSS_PORT: 5114
    PG_DB_COLLECTION_ID: 1
  <<: *deploy_flask_template
  environment:
    name: $ENVIRONMENT_NAME_FLASK
    url: $ENVIRONMENT_URL_FLASK
  rules:
    - if: '$CI_COMMIT_BRANCH == "prev"'

deploy_prev_mss:
  stage: deploy_prev_mss
  tags:
    - tank
  variables:
    FLASK_PORT: 5444
    PG_DB_PORT: 5334
    MSS_PORT: 5114
    PG_DB_COLLECTION_ID: 1
  <<: *deploy_mss_template
  environment:
    name: $ENVIRONMENT_NAME_MSS
    url: $ENVIRONMENT_URL_MSS
  rules:
    - if: '$CI_COMMIT_BRANCH == "prev" && $MSS_DISABLE_DEPLOY != "true"'

# Production Environment
deploy_main_db:
  stage: deploy_main_db
  tags:
    - tank
  variables:
    FLASK_PORT: 5445
    PG_DB_PORT: 5335
    MSS_PORT: 5115
    PG_DB_COLLECTION_ID: 1
  <<: *deploy_db_template
  environment:
    name: $ENVIRONMENT_NAME_DB
    url: $ENVIRONMENT_URL_DB
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $PG_DB_DISABLE_DEPLOY != "true"'

deploy_main_flask:
  stage: deploy_main_flask
  tags:
    - tank
  variables:
    FLASK_PORT: 5445
    PG_DB_PORT: 5335
    MSS_PORT: 5115
    PG_DB_COLLECTION_ID: 1
  <<: *deploy_flask_template
  environment:
    name: $ENVIRONMENT_NAME_FLASK
    url: $ENVIRONMENT_URL_FLASK
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy_main_mss:
  stage: deploy_main_mss
  tags:
    - tank
  variables:
    FLASK_PORT: 5445
    PG_DB_PORT: 5335
    MSS_PORT: 5115
    PG_DB_COLLECTION_ID: 1
  <<: *deploy_mss_template
  environment:
    name: $ENVIRONMENT_NAME_MSS
    url: $ENVIRONMENT_URL_MSS
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $MSS_DISABLE_DEPLOY != "true"'
