services:
  powertwin-solver:
    container_name: powertwin-solver
    build: .
    ports:
      - "8080:8080"
    volumes:
      - powertwin_data:/app/powertwin-db
    depends_on:
      - db
    tty: true 


  db:
    image: postgres:latest
    container_name: powertwin-db
    environment:
      POSTGRES_DB: powertwin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - powertwin_data:/app/powertwin-db

volumes:
  powertwin-solver:
  postgres_data:
  powertwin_data: