services:
  powertwin-solver-pg:
    image: postgres:latest
    container_name: ${NAME_PREFIX:-}powertwin-solver-pg
    environment:
      - POSTGRES_DB=powertwin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - PG_DB_TOKEN_ADMIN=${PG_DB_TOKEN_ADMIN}
    ports:
      - "${PG_DB_PORT}:5432"
    volumes:
      - /mnt/g/powertwin_data:/app/powertwin-solver-pg
      - /mnt/g/postgres_data:/var/lib/postgresql/data

  powertwin-solver-flask:
    container_name: ${NAME_PREFIX:-}powertwin-solver-flask
    build: 
      context: ./app
    ports:
      - "${FLASK_PORT}:8080"
    environment:
      - FLASK_MSS_BASE_URL=${FLASK_MSS_BASE_URL}
      - PG_DB_TOKEN_ADMIN=${PG_DB_TOKEN_ADMIN}
    volumes:
      - /mnt/g/powertwin_data:/app/powertwin-solver-pg
    depends_on:
      - powertwin-solver-pg
    tty: true 

  powertwin-solver-mss:
    container_name: ${NAME_PREFIX:-}powertwin-solver-mss
    build: 
      context: ./mss
    ports:
      - "${MSS_PORT}:8080"
    environment:
      - MSS_FLASK_BASE_URL=${MSS_FLASK_BASE_URL}
      - MSS_SLACK_VERIFICATION_TOKEN=${MSS_SLACK_VERIFICATION_TOKEN}
      - MSS_SLACK_SIGNING_SECRET=${MSS_SLACK_SIGNING_SECRET}
      - MSS_SLACK_WEBHOOK_URL=${MSS_SLACK_WEBHOOK_URL}
      - MSS_SLACK_CHANNEL=${MSS_SLACK_CHANNEL}
      - PG_DB_TOKEN_ADMIN=${PG_DB_TOKEN_ADMIN}
      - FLASK_PORT=${FLASK_PORT}
    depends_on:
      - powertwin-solver-pg
    links:
      - powertwin-solver-pg

networks:
  default:
    name: gitlab-network
    external: true

volumes:
  powertwin-solver-flask:
  postgres_data:
  powertwin_data: