services:
  powertwin-solver-flask:
    container_name: powertwin-solver-flask
    build: .
    ports:
      - "${SOLVER_PORT}:8080"
    volumes:
      - ./app/powertwin_data:/app/powertwin-db-pg
    depends_on:
      - powertwin-db-pg
    tty: true 


  powertwin-db-pg:
    image: postgres:latest
    container_name: powertwin-db-pg
    environment:
      POSTGRES_DB: powertwin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "${PG_DB_PORT}:5432"
    volumes:
      - ./app/powertwin_data:/app/powertwin-db-pg
      - postgres_data:/var/lib/postgresql/data

volumes:
  powertwin-solver-flask:
  postgres_data:
  powertwin_data: