{{- $component := "pg" }}
{{- $name := include "solver.componentName" (dict "ctx" . "component" $component) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "solver.labels" . | nindent 4 }}
    {{- include "solver.selectorLabels" (dict "ctx" . "component" $component) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.pg.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "solver.selectorLabels" (dict "ctx" . "component" $component) | nindent 4 }}
