apiVersion: v1
kind: Secret
metadata:
  name: {{ include "solver.secretName" . }}
  labels:
    {{- include "solver.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Consumed by pg/pgbouncer/flask/mss.
  PG_DB_TOKEN_ADMIN: {{ .Values.secrets.pgAdminToken | quote }}
  API_SOLVER_TOKEN: {{ .Values.secrets.apiSolverToken | quote }}
  MSS_SLACK_VERIFICATION_TOKEN: {{ .Values.secrets.slackVerificationToken | quote }}
  MSS_SLACK_SIGNING_SECRET: {{ .Values.secrets.slackSigningSecret | quote }}
  MSS_SLACK_WEBHOOK_URL: {{ .Values.secrets.slackWebhookUrl | quote }}
  MAIN_PG_PASSWORD: {{ .Values.secrets.mainPgPassword | quote }}
